version: "3"
services:
  sparkmaster: 
    build: "./spark_master"
    expose:
      - "7077" # indicate that this service is listening on this port, exposing it to other services
    networks:
      - spark_intranet
  sparkworker:
    build: "./spark_worker"
    depends_on:
      - sparkmaster
    networks:
      - spark_intranet
    deploy:
      replicas: 2
  sparkdriver:
    build: "./sparkdriver"
    depends_on:
      - sparkmaster
    networks:
      - spark_intranet
networks:
  spark_intranet:
