version: "3.8"

services:
  s3:
    image: localhost:5000/s3:latest
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
    networks:
      - intranet
    ports:
      - "4566"
    environment:
      - DEBUG=${DEBUG:-0}
      - SERVICES=s3
      - GATEWAY_LISTEN=4566
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  db:
    image: localhost:5000/db:latest
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
    networks:
      - intranet
    ports:
      - "3306"
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1

  taskq:
    image: localhost:5000/taskq:latest
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
    networks:
      - intranet
    ports:
      - "5672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guestpw"

  webfrontend:
    image: localhost:5000/webfrontend:latest
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
    depends_on:
      - taskq
    networks:
      - intranet
    ports:
      - "8080:80"
    environment:
      WEB_FRONTEND_PORT: "80"
      APP_BROKER_URI: "amqp://guest:guestpw@taskq"
      MARIADB_USER_USERNAME: "root"
      MARIADB_USER_PASSWORD: ""
      MARIADB_HOSTNAME: "db"
      MARIADB_PORT: "3306"
      S3_HOSTNAME: "s3"
      S3_PORT: "4566"
      S3_ACCESS_KEY_ID: "test"
      S3_SECRET_ACCESS_KEY: "test"
      S3_BUCKET_NAME: mybucket

  cpmapper:
    image: localhost:5000/cpmapper:latest
    # ensure that the container is stopped gracefully (this signal may be caught at runtime)
    stop_signal: SIGTERM
    stop_grace_period: 30s
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
    depends_on:
      - taskq
    networks:
      - intranet
    environment:
      APP_BROKER_URI: "amqp://guest:guestpw@taskq"
      MARIADB_USER_USERNAME: "root"
      MARIADB_USER_PASSWORD: ""
      MARIADB_HOSTNAME: "db"
      MARIADB_PORT: "3306"
      S3_HOSTNAME: "s3"
      S3_PORT: "4566"
      S3_ACCESS_KEY_ID: "test"
      S3_SECRET_ACCESS_KEY: "test"
      S3_BUCKET_NAME: mybucket

  cpreducer:
    image: localhost:5000/cpreducer:latest
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
    depends_on:
      - taskq
    networks:
      - intranet
    environment:
      APP_BROKER_URI: "amqp://guest:guestpw@taskq"
      MARIADB_USER_USERNAME: "root"
      MARIADB_USER_PASSWORD: ""
      MARIADB_HOSTNAME: "db"
      MARIADB_PORT: "3306"
      S3_HOSTNAME: "s3"
      S3_PORT: "4566"
      S3_ACCESS_KEY_ID: "test"
      S3_SECRET_ACCESS_KEY: "test"
      S3_BUCKET_NAME: mybucket

networks:
  intranet:
