version: "3.8"

services:
  s3:
    image: localstack/localstack:s3-latest
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
    networks:
      - intranet
    ports:
      - "4566"
    environment:
      - DEBUG=${DEBUG:-0}
      - SERVICES=s3
      - GATEWAY_LISTEN=4566
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  db:
    image: mariadb:11.3
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
    networks:
      - intranet
    ports:
      - "3306"
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1

  taskq:
    build:
      context: rabbitmq
      dockerfile: rabbitmq.Dockerfile
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
    networks:
      - intranet
    ports:
      - "5672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guestpw"

  webfrontend:
    build:
      context: web-frontend
      dockerfile: webserver.Dockerfile
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
    depends_on:
      - taskq
    networks:
      - intranet
    ports:
      - "8080:80"
    environment:
      WEB_FRONTEND_PORT: "80"
      APP_BROKER_URI: "amqp://guest:guestpw@taskq"
      MARIADB_USER_USERNAME: "root"
      MARIADB_USER_PASSWORD: ""
      MARIADB_HOSTNAME: "db"
      MARIADB_PORT: "3306"
      S3_HOSTNAME: "s3"
      S3_PORT: "4566"
      S3_ACCESS_KEY_ID: "test"
      S3_SECRET_ACCESS_KEY: "test"
      S3_BUCKET_NAME: mybucket

  cpmapper:
    build:
      context: script_workers
      dockerfile: cpmapper.Dockerfile
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
    depends_on:
      - taskq
    networks:
      - intranet
    environment:
      APP_BROKER_URI: "amqp://guest:guestpw@taskq"
      MARIADB_USER_USERNAME: "root"
      MARIADB_USER_PASSWORD: ""
      MARIADB_HOSTNAME: "db"
      MARIADB_PORT: "3306"
      S3_HOSTNAME: "s3"
      S3_PORT: "4566"
      S3_ACCESS_KEY_ID: "test"
      S3_SECRET_ACCESS_KEY: "test"
      S3_BUCKET_NAME: mybucket

  cpreducer:
    build:
      context: script_workers
      dockerfile: cpreducer.Dockerfile
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
    depends_on:
      - taskq
    networks:
      - intranet
    environment:
      APP_BROKER_URI: "amqp://guest:guestpw@taskq"
      MARIADB_USER_USERNAME: "root"
      MARIADB_USER_PASSWORD: ""
      MARIADB_HOSTNAME: "db"
      MARIADB_PORT: "3306"
      S3_HOSTNAME: "s3"
      S3_PORT: "4566"
      S3_ACCESS_KEY_ID: "test"
      S3_SECRET_ACCESS_KEY: "test"
      S3_BUCKET_NAME: mybucket

networks:
  intranet:

