version: "3.8"

services:
  s3:
    image: localstack/localstack:s3-latest
    restart: always
    networks:
      - intranet
    ports:
      - "4566"
    environment:
      - DEBUG=${DEBUG:-0}
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  db:
    image: mariadb:11.3
    restart: always
    networks:
      - intranet
    ports:
      - "3306"
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1

  taskq:
    build:
      context: rabbitmq
      dockerfile: rabbitmq.Dockerfile
    restart: always
    networks:
      - intranet
    ports:
      - "5672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guestpw"

  dbwatcher:
    build:
      context: script_workers
      dockerfile: dbwatcher.Dockerfile
    restart: always
    depends_on:
      - taskq
    networks:
      - intranet
    environment:
      APP_BROKER_URI: "amqp://guest:guestpw@taskq"
      MARIADB_USER_USERNAME: "root"
      MARIADB_USER_PASSWORD: ""
      MARIADB_HOSTNAME: "db"
      MARIADB_PORT: "3306"

  webfrontend:
    build:
      context: web-frontend
      dockerfile: Dockerfile
    restart: always
    networks:
      - intranet
    ports:
      - "8080:80"
    environment:
      WEB_FRONTEND_PORT: "80"

  cpmapper:
    build:
      context: script_workers
      dockerfile: cpmapper.Dockerfile
    restart: always
    depends_on:
      - taskq
    networks:
      - intranet
    environment:
      APP_BROKER_URI: "amqp://guest:guestpw@taskq"

  cpreducer:
    build:
      context: script_workers
      dockerfile: cpreducer.Dockerfile
    restart: always
    depends_on:
      - taskq
    networks:
      - intranet
    environment:
      APP_BROKER_URI: "amqp://guest:guestpw@taskq"

networks:
  intranet:

